### ISSUE TITLE
PatLaFon's tracking issue

### ISSUE THREAD

**Issue by Pat-Lafon** [PurduePL/purduepl.github.io#65]
A couple ideas of what I want to do. Open to additions/comments/suggestions.

- [ ] Update dependencies/Resolve Dependabot pr's
- [ ] Updating lists of Professors/Students(/Postdocs?)
- [ ] Add an alumni section and move graduated students to it
- [ ] Update the seminar schedule with Fall's seminars
- [ ] Add a template issue for adding people + Document this
- [ ] Add a favicon.ico
- [ ] Clean up unused files

**Comment by Pat-Lafon** [comment]
Looking at this list, it's in a pretty good spot and I can't think of many improvements I'm pushing to make at the moment so I'm closing this issue.
